//
// Created by Kirill Minaev on 25.06.2024.
//

#ifndef LIGHTRAYENGINE_EDITORCONFIGURATIONSETTINGSUTILS_H
#define LIGHTRAYENGINE_EDITORCONFIGURATIONSETTINGSUTILS_H


class EditorConfigurationSettingsUtils {

};


#endif //LIGHTRAYENGINE_EDITORCONFIGURATIONSETTINGSUTILS_H
