//
// Created by MrFlyingChip on 25.06.2024.
//

#ifndef LIGHTRAYENGINE_EDITORCONFIGURATIONSETTINGS_H
#define LIGHTRAYENGINE_EDITORCONFIGURATIONSETTINGS_H


class EditorConfigurationSettings {

};


#endif //LIGHTRAYENGINE_EDITORCONFIGURATIONSETTINGS_H
